version: '2'
services:
  postgres:
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=chat
      - POSTGRES_USER=chat
      - POSTGRES_PASSWORD=chat
      - MAX_CONNECTIONS=1000
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  chat-1:
    image: distributed-chat:latest
    build:
      dockerfile: ./Dockerfile
      context: .
#    scale: 2
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=chat
      - DATABASE_PASSWORD=chat
      - REDIS_HOST=redis:6379
      - HOSTNAME=chat-1
    depends_on:
      - postgres
      - redis
  chat-2:
    image: distributed-chat:latest
    build:
      dockerfile: ./Dockerfile
      context: .
#    scale: 2
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=chat
      - DATABASE_PASSWORD=chat
      - REDIS_HOST=redis:6379
      - HOSTNAME=chat-2
    depends_on:
      - postgres
      - redis
  chat-3:
    image: distributed-chat:latest
    build:
      dockerfile: ./Dockerfile
      context: .
#    scale: 2
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=chat
      - DATABASE_PASSWORD=chat
      - REDIS_HOST=redis:6379
      - HOSTNAME=chat-3
    depends_on:
      - postgres
      - redis
  load_balance:
    image: nginx:stable-alpine
    ports:
    - "8080:80"
    volumes:
    - ./load-balance-nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - chat-1
      - chat-2
      - chat-3