micronaut:
  application:
    name: distributedChat
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/chat
    driverClassName: org.postgresql.Driver
    username: chat
    password: chat
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:migrations
