micronaut:
  application:
    name: distributedChat
    instance:
      id: ${HOSTNAME:}
datasources:
  default:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/chat
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER:chat}
    password: ${DATABASE_PASSWORD:chat}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
    maximum-pool-size: 10


jpa.default.properties.hibernate.hbm2ddl.auto: update
flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:migrations

redis:
  uri: "redis://${REDIS_HOST:localhost:6379}"


chat:
  server:
    hostname: ${HOSTNAME:localhost}
grpc:
  server:
    port: 8081